// Generated by mds. Do not edit. Source: .mds/test/greet.ts.md. Source-Hash: 3ec5798a948ce2f495c0cb72c212b7af22cb040ca0aba2d8d5ded4e9f956bc9c.

import { describe, expect, it } from "vitest";
import { greet } from "../src/greet";

describe("greet", () => {
  it("returns greeting with name", () => {
    expect(greet({ name: "World" })).toBe("Hello, World!");
  });

  it("uses Anonymous when name is missing", () => {
    expect(greet({})).toBe("Hello, Anonymous!");
  });
});
