// Generated by mds. Do not edit. Source: .mds/source/greet.ts.md. Source-Hash: 62a95b6b5a08a2e65cdba70a302a92ddf5602a8d265a0076f0a6242eab31ea67.

export interface GreetOptions {
  name?: string;
}

export function greet(options: GreetOptions): string {
  const name = options.name?.trim() || "Anonymous";
  return `Hello, ${name}!`;
}
