// Generated by mds. Do not edit. Source: .mds/test/foo/source-map.ts.md. Source-Hash: 08d38faa2608ba6bd9c1ace6625b2161f8cc4f02bf62910b452ef2854373890b.

import { describe, expect, it } from "vitest";
import { two } from "../../src/foo/source-map";

describe("source-map", () => {
  it("returns incremented value", () => {
    expect(two()).toBe(2);
  });
});
