// Generated by mds. Do not edit. Source: .mds/source/foo/bar.ts.md. Source-Hash: 0036c8080e86fb790fbc0a5355b20bbf99cfd4d5881c2283ad2d9f96e44d94b8.

export type Bar = Util;

export const bar: Bar = util;

expect(bar).toBe("ok");
