// Generated by mds. Do not edit. Source: .mds/source/foo/source-map.ts.md. Source-Hash: 14d7595ae5575b9848219ebc150254cb92bc728fb4be50b9a10ac325f9d55eea.

export const one = 1;

export function two(): number {
  return one + 1;
}

export const twoResult = two();
export const confirmed = twoResult === 2;
export type TwoResult = typeof twoResult;
