// Generated by mds. Do not edit. Source: .mds/source/foo/util.ts.md. Source-Hash: edf763f293c1831131c29176eb3b55e6b36e85a0317a00e656ed2832ab0f3efb.

export type Util = string;

export const util = "ok";

expect(util).toBe("ok");
